[build]
  publish = "/opt/build/repo"
  command = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"

[context.production.environment]
  PORT = "8501"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
